In [7]:
import pandas as pd

In [8]:
df = pd.read_csv('D:/Projects/Credit Card Default Prediction/notebook/data/Cleaned_Dataset.csv')
df.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,20000.0,2,2,1,24,2,2,-1,-1,-2,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,120000.0,2,2,2,26,-1,2,0,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,90000.0,2,2,2,34,0,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,50000.0,2,2,1,37,0,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,50000.0,1,2,1,57,-1,0,-1,0,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

In [9]:
# Independent and Dependent Features:

X = df.drop(labels = ['default.payment.next.month'], axis=1)
Y = df[['default.payment.next.month']]

In [10]:
X

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,20000.0,2,2,1,24,2,2,-1,-1,-2,...,689.0,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0
1,120000.0,2,2,2,26,-1,2,0,0,0,...,2682.0,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0
2,90000.0,2,2,2,34,0,0,0,0,0,...,13559.0,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0
3,50000.0,2,2,1,37,0,0,0,0,0,...,49291.0,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0
4,50000.0,1,2,1,57,-1,0,-1,0,0,...,35835.0,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,220000.0,1,3,1,39,0,0,0,0,0,...,208365.0,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0
29996,150000.0,1,3,2,43,-1,-1,-1,-1,0,...,3502.0,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0
29997,30000.0,1,2,2,37,4,3,2,-1,0,...,2758.0,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0
29998,80000.0,1,3,1,41,1,-1,0,0,0,...,76304.0,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0
29999,50000.0,1,2,1,46,0,0,0,0,0,...,49764.0,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0

In [11]:
Y

       default.payment.next.month
0                               1
1                               1
2                               0
3                               0
4                               0
...                           ...
29995                           0
29996                           0
29997                           1
29998                           1
29999                           1

[30000 rows x 1 columns]

In [12]:
# Segregating Numerical and Categorical Variables

categorical_cols = X.select_dtypes(include='object').columns
numerical_cols = X.select_dtypes(exclude='object').columns

In [13]:
categorical_cols

Index([], dtype='object')

In [14]:
numerical_cols

Index(['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0', 'PAY_2',
       'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6'],
      dtype='object')

In [15]:
from sklearn.impute import SimpleImputer  # Handling Missing Values
from sklearn.preprocessing import StandardScaler  # Handling Feature Scaling
from sklearn.preprocessing import OrdinalEncoder  # Ordinal Encoding

# Pipeline
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [16]:
# Numerical Pipeline:

num_pipeline = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler())        
    ]
)

# Categorical Pipeline:

cat_pipeline = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('ordinalencoder', OrdinalEncoder()),
        ('scaler', StandardScaler())
    ]
)

preprocessor = ColumnTransformer([
    ('num_pipeline', num_pipeline, numerical_cols),
    ('cat_pipeline', cat_pipeline, categorical_cols)
])

In [17]:
# Train Test Split:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.30, random_state=30)

In [18]:
X_train = pd.DataFrame(preprocessor.fit_transform(X_train), columns=preprocessor.get_feature_names_out())
X_test = pd.DataFrame(preprocessor.transform(X_test), columns=preprocessor.get_feature_names_out())

In [19]:
X_train.head()

,num_pipeline__LIMIT_BAL,num_pipeline__SEX,num_pipeline__EDUCATION,num_pipeline__MARRIAGE,num_pipeline__AGE,num_pipeline__PAY_0,num_pipeline__PAY_2,num_pipeline__PAY_3,num_pipeline__PAY_4,num_pipeline__PAY_5,...,num_pipeline__BILL_AMT3,num_pipeline__BILL_AMT4,num_pipeline__BILL_AMT5,num_pipeline__BILL_AMT6,num_pipeline__PAY_AMT1,num_pipeline__PAY_AMT2,num_pipeline__PAY_AMT3,num_pipeline__PAY_AMT4,num_pipeline__PAY_AMT5,num_pipeline__PAY_AMT6
0,-1.139003,-1.231086,0.189892,0.855242,-1.031921,-0.872883,-0.720412,-0.694606,-0.665419,-1.532938,...,-0.667972,-0.683707,-0.669670,-0.629882,-0.259967,-0.219680,-0.284034,-0.262225,-0.169920,-0.289958
1,-0.138540,-1.231086,-1.076056,-1.060909,0.599775,0.901613,-1.558100,-0.694606,-0.665419,-0.647261,...,-0.651531,-0.586762,-0.662746,-0.652089,-0.333370,-0.166585,0.008592,-0.313948,-0.305063,-0.289958
2,0.631048,0.812291,-1.076056,0.855242,-0.705581,1.788862,1.792653,1.821359,1.910872,2.009769,...,1.124524,1.227215,1.416612,1.498716,0.010071,-0.060316,-0.284034,0.080871,-0.057618,-0.021965
3,1.477594,-1.231086,-1.076056,-1.060909,0.382216,0.901613,-1.558100,-1.533261,-1.524183,-0.647261,...,-0.674425,-0.671125,-0.651354,-0.533990,-0.333370,-0.237431,-0.284034,-0.268127,0.140338,-0.289958
4,0.861924,-1.231086,0.189892,-1.060909,0.926114,0.014365,0.117276,0.144049,0.193345,0.238416,...,1.080023,1.177725,1.212598,1.283075,0.121951,-0.059174,-0.055687,-0.028477,-0.038076,-0.067667

In [20]:
X_test.head()

,num_pipeline__LIMIT_BAL,num_pipeline__SEX,num_pipeline__EDUCATION,num_pipeline__MARRIAGE,num_pipeline__AGE,num_pipeline__PAY_0,num_pipeline__PAY_2,num_pipeline__PAY_3,num_pipeline__PAY_4,num_pipeline__PAY_5,...,num_pipeline__BILL_AMT3,num_pipeline__BILL_AMT4,num_pipeline__BILL_AMT5,num_pipeline__BILL_AMT6,num_pipeline__PAY_AMT1,num_pipeline__PAY_AMT2,num_pipeline__PAY_AMT3,num_pipeline__PAY_AMT4,num_pipeline__PAY_AMT5,num_pipeline__PAY_AMT6
0,-1.139003,-1.231086,0.189892,-1.060909,0.164656,0.014365,0.117276,0.144049,0.193345,2.009769,...,-0.517827,-0.495906,-0.481219,-0.521625,-0.202513,-0.178393,-0.243247,-0.313948,-0.277781,-0.234427
1,0.323213,0.812291,0.189892,0.855242,1.034894,0.901613,-1.558100,-1.533261,-1.524183,-1.532938,...,-0.674425,-0.671125,-0.662746,-0.652089,-0.333370,-0.237431,-0.284034,-0.313948,-0.305063,-0.289958
2,1.862388,-1.231086,-1.076056,0.855242,-0.923141,0.014365,-0.720412,-0.694606,0.193345,-0.647261,...,-0.450088,-0.041830,-0.367911,-0.075875,0.603235,0.395304,1.882136,0.877935,1.885017,-0.269467
3,0.323213,0.812291,-1.076056,0.855242,-0.705581,-1.760132,-1.558100,-1.533261,-1.524183,-1.532938,...,-0.674468,-0.671172,-0.652030,-0.620966,-0.333370,-0.237431,-0.284034,-0.270647,-0.187114,-0.211604
4,0.015378,0.812291,-1.076056,0.855242,0.382216,0.014365,0.117276,0.144049,0.193345,0.238416,...,-0.364491,-0.309084,-0.413231,-0.592753,-0.041678,-0.040636,0.068238,-0.037628,-0.081284,0.127691

In [21]:
# Model Training:

from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [22]:
regression = LinearRegression()
regression.fit(X_train, y_train)

LinearRegression()

In [23]:
regression.coef_

array([[-0.01380848, -0.00626904, -0.01087068, -0.01425497,  0.01080939,
         0.10596977,  0.02474866,  0.01556321,  0.0030201 ,  0.01000553,
        -0.00232154, -0.04394629,  0.01341836, -0.00100774, -0.01193873,
         0.00384942,  0.01061765, -0.01169964, -0.00138038, -0.00122572,
        -0.00695406, -0.00644301, -0.00187973]])

In [24]:
regression.intercept_

array([0.22380952])

In [25]:
import numpy as np

def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [26]:
# Train Multiple Models:
# Model Evaluation:

models = {
    'LinearRegression' : LinearRegression(),
    'Lasso' : Lasso(),
    'Ridge' : Ridge(),
    'Elasticnet' : ElasticNet()
}

trained_model_list = []
model_list = []
r2_list = []

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train)
    
    # Make Prediction:
    y_pred = model.predict(X_test)
    
    mae, rmse, r2_square = evaluate_model(y_test, y_pred)
    
    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])
    
    print('Model Training Performance')
    print('RMSE:', rmse)
    print('MAE:', mae)
    print('r2 Score:', r2_square*100)
    
    r2_list.append(r2_square)
    
    print('='*35)
    print('\n')

LinearRegression
Model Training Performance
RMSE: 0.3857551167260671
MAE: 0.306887607542677
r2 Score: 11.864196937126248
===================================


Lasso
Model Training Performance
RMSE: 0.41099146386649715
MAE: 0.3426328042328043
r2 Score: -0.044813513324037935
===================================


Ridge
Model Training Performance
RMSE: 0.3857551190381274
MAE: 0.30688806938895163
r2 Score: 11.864195880625461
===================================


Elasticnet
Model Training Performance
RMSE: 0.41099146386649715
MAE: 0.3426328042328043
r2 Score: -0.044813513324037935
===================================

### Percentage whichever getting from LinearRegression, Lasso, Ridge and Elasticnet Model is not Acceptable for Training a Model.

### So, Let's Try with RandomForestRegressor Model

In [27]:
import warnings
warnings.filterwarnings("ignore")

from sklearn.ensemble import RandomForestRegressor

reg_rf = RandomForestRegressor()
reg_rf.fit(X_train, y_train)

RandomForestRegressor()

In [28]:
y_pred = reg_rf.predict(X_test)

In [29]:
reg_rf.score(X_train, y_train)

0.8866637262629676

#### Percentage getting from RandomForestRegressor Model is acceptable to Train a Model.

In [30]:
import pickle

# Create and Train the RandomForestRegressor Model
model = RandomForestRegressor()

# Save the Model to a '.pkl' File:
filename = 'model.pkl'
with open(filename, 'wb') as file:
    pickle.dump(model, file)